---
rules:
  - id: '@secretlint/secretlint-rule-preset-recommend'
    rules:
      - id: '@secretlint/secretlint-rule-aws'
        # they are not considered secret, sensitive, or confidential information.
        # https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-identifiers.html
        allowMessageIds: [AWSAccountID, AWSAccessKeyID]
